# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/util/util.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rpc import common_pb2 as rpc_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rpc/util/util.proto\x1a\x10rpc/common.proto2d\n\x11TransformLocation\x12\x1f\n\x04ToXY\x12\x12.LatitudeLongitude\x1a\x03.XY\x12.\n\x13ToLatitudeLongitude\x12\x03.XY\x1a\x12.LatitudeLongitudeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.util.util_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFORMLOCATION._serialized_start=41
  _TRANSFORMLOCATION._serialized_end=141
# @@protoc_insertion_point(module_scope)
