# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import common_pb2 as rpc_dot_common__pb2


class TransformLocationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ToXY = channel.unary_unary(
                '/TransformLocation/ToXY',
                request_serializer=rpc_dot_common__pb2.LatitudeLongitude.SerializeToString,
                response_deserializer=rpc_dot_common__pb2.XY.FromString,
                )
        self.ToLatitudeLongitude = channel.unary_unary(
                '/TransformLocation/ToLatitudeLongitude',
                request_serializer=rpc_dot_common__pb2.XY.SerializeToString,
                response_deserializer=rpc_dot_common__pb2.LatitudeLongitude.FromString,
                )


class TransformLocationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ToXY(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToLatitudeLongitude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransformLocationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ToXY': grpc.unary_unary_rpc_method_handler(
                    servicer.ToXY,
                    request_deserializer=rpc_dot_common__pb2.LatitudeLongitude.FromString,
                    response_serializer=rpc_dot_common__pb2.XY.SerializeToString,
            ),
            'ToLatitudeLongitude': grpc.unary_unary_rpc_method_handler(
                    servicer.ToLatitudeLongitude,
                    request_deserializer=rpc_dot_common__pb2.XY.FromString,
                    response_serializer=rpc_dot_common__pb2.LatitudeLongitude.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransformLocation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransformLocation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ToXY(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TransformLocation/ToXY',
            rpc_dot_common__pb2.LatitudeLongitude.SerializeToString,
            rpc_dot_common__pb2.XY.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToLatitudeLongitude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TransformLocation/ToLatitudeLongitude',
            rpc_dot_common__pb2.XY.SerializeToString,
            rpc_dot_common__pb2.LatitudeLongitude.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
