services:
  ktor:
    image: postomat-back-ktor:0.0.1
    ports:
      - "8080:8080"
    restart: always
    environment:
      - REGION_PORT=8082
      - POSTOMAT_PORT=8083
      - MODEL_PORT=3110
      - LOCATION_PORT=3110
    links:
      - regions
      - postomat
    networks:
      - backend
    volumes:
      - ./cache.json:/cache.json
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./dataset/:/dataset
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  regions:
    image: postomat-back-regions:0.0.1
    ports:
      - "8082:8082"
    restart: always
    environment:
      - REGION_PORT=8082
      - MODEL_PORT=3110
      - LOCATION_PORT=3110
      - "DATABASE_CONNECTOR=jdbc:postgresql://db:5432/postgres"
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - POSTOMAT_PORT=8083
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  postomat:
    image: postomat-back-postomat:0.0.1
    ports:
      - "8083:8083"
    restart: always
    environment:
      - REGION_PORT=8082
      - "DATABASE_CONNECTOR=jdbc:postgresql://db:5432/postgres"
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - POSTOMAT_PORT=8083
      - MODEL_PORT=3110
      - LOCATION_PORT=3110
    networks:
      - backend
    links:
      - db
      - regions
    depends_on:
      - db
      - regions

volumes:
  db:
    driver: local
networks:
  backend:
