# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/model/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rpc import common_pb2 as rpc_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rpc/model/model.proto\x1a\x10rpc/common.proto\":\n\x04\x42\x42ox\x12\x17\n\nupper_left\x18\x01 \x01(\x0b\x32\x03.XY\x12\x19\n\x0c\x62ottom_right\x18\x02 \x01(\x0b\x32\x03.XY\"\x1b\n\nAssessment\x12\r\n\x05score\x18\x01 \x03(\x02\"6\n\x08InBounds\x12\x15\n\x06\x62ounds\x18\x01 \x01(\x0b\x32\x05.BBox\x12\x13\n\x06points\x18\x02 \x03(\x0b\x32\x03.XY\"$\n\rAssessRequest\x12\x13\n\x06points\x18\x01 \x03(\x0b\x32\x03.XY\"y\n\x13ModelInitialization\x12\x16\n\x05model\x18\x01 \x01(\x0e\x32\x07.Models\x12\t\n\x01R\x18\x02 \x01(\x05\x12\t\n\x01\x42\x18\x03 \x01(\x05\x12\x1d\n\x10\x61lready_deployed\x18\x04 \x03(\x0b\x32\x03.XY\x12\t\n\x01\x43\x18\x05 \x01(\x05\x12\n\n\x02R2\x18\x06 \x01(\x05\"\"\n\x10NewModelResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08*\\\n\x06Models\x12\x18\n\x14ONLY_DISTANCES_MODEL\x10\x00\x12\x19\n\x15POSTOFFICES_AS_COEFFS\x10\x01\x12\x1d\n\x19\x44\x45NY_IF_POSTOFFICE_NEARBY\x10\x02\x32\x8d\x01\n\x05Model\x12\x33\n\x08NewModel\x12\x14.ModelInitialization\x1a\x11.NewModelResponse\x12%\n\x06\x41ssess\x12\x0e.AssessRequest\x1a\x0b.Assessment\x12(\n\x0e\x41ssessInBounds\x12\t.InBounds\x1a\x0b.Assessmentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.model.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELS._serialized_start=385
  _MODELS._serialized_end=477
  _BBOX._serialized_start=43
  _BBOX._serialized_end=101
  _ASSESSMENT._serialized_start=103
  _ASSESSMENT._serialized_end=130
  _INBOUNDS._serialized_start=132
  _INBOUNDS._serialized_end=186
  _ASSESSREQUEST._serialized_start=188
  _ASSESSREQUEST._serialized_end=224
  _MODELINITIALIZATION._serialized_start=226
  _MODELINITIALIZATION._serialized_end=347
  _NEWMODELRESPONSE._serialized_start=349
  _NEWMODELRESPONSE._serialized_end=383
  _MODEL._serialized_start=480
  _MODEL._serialized_end=621
# @@protoc_insertion_point(module_scope)
