# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc.model import model_pb2 as rpc_dot_model_dot_model__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewModel = channel.unary_unary(
                '/Model/NewModel',
                request_serializer=rpc_dot_model_dot_model__pb2.ModelInitialization.SerializeToString,
                response_deserializer=rpc_dot_model_dot_model__pb2.NewModelResponse.FromString,
                )
        self.Assess = channel.unary_unary(
                '/Model/Assess',
                request_serializer=rpc_dot_model_dot_model__pb2.AssessRequest.SerializeToString,
                response_deserializer=rpc_dot_model_dot_model__pb2.Assessment.FromString,
                )
        self.AssessInBounds = channel.unary_unary(
                '/Model/AssessInBounds',
                request_serializer=rpc_dot_model_dot_model__pb2.InBounds.SerializeToString,
                response_deserializer=rpc_dot_model_dot_model__pb2.Assessment.FromString,
                )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Assess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessInBounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewModel': grpc.unary_unary_rpc_method_handler(
                    servicer.NewModel,
                    request_deserializer=rpc_dot_model_dot_model__pb2.ModelInitialization.FromString,
                    response_serializer=rpc_dot_model_dot_model__pb2.NewModelResponse.SerializeToString,
            ),
            'Assess': grpc.unary_unary_rpc_method_handler(
                    servicer.Assess,
                    request_deserializer=rpc_dot_model_dot_model__pb2.AssessRequest.FromString,
                    response_serializer=rpc_dot_model_dot_model__pb2.Assessment.SerializeToString,
            ),
            'AssessInBounds': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessInBounds,
                    request_deserializer=rpc_dot_model_dot_model__pb2.InBounds.FromString,
                    response_serializer=rpc_dot_model_dot_model__pb2.Assessment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Model', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/NewModel',
            rpc_dot_model_dot_model__pb2.ModelInitialization.SerializeToString,
            rpc_dot_model_dot_model__pb2.NewModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Assess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/Assess',
            rpc_dot_model_dot_model__pb2.AssessRequest.SerializeToString,
            rpc_dot_model_dot_model__pb2.Assessment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssessInBounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/AssessInBounds',
            rpc_dot_model_dot_model__pb2.InBounds.SerializeToString,
            rpc_dot_model_dot_model__pb2.Assessment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
