version: "3"

services:
  sample:
    container_name: postomat-map-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    restart: always
